package org.graphify.core.api.extraction;

import junit.framework.TestCase;
import org.graphify.core.kernel.models.LabeledText;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.test.TestGraphDatabaseFactory;

public class FeaturesTest extends TestCase {

    private static GraphDatabaseService setUpDb()
    {
        return new TestGraphDatabaseFactory().newImpermanentDatabaseBuilder().newGraphDatabase();
    }

    public void testExtractFeatures() throws Exception {
        GraphDatabaseService db = setUpDb();
        LabeledText labeledText = new LabeledText();
        labeledText.setLabel(new String[] { "positive" });
        labeledText.setText(new String[] {
                "It has the kind of vision and ambition that is rare in movies today. It is not a formula movie, but a thoughtful, carefully observed story.",
                "Valentine's Day is being marketed as a Date Movie. I think it's more of a First-Date Movie. If your date likes it, do not date that person again. And if you like it, there may not be a second date.",
                "At least no movie has yet been inspired by 'It's a Small World.'",
                "Oh, what a lovely film. I was almost hugging myself while I watched it.",
                "It is a personal triumph for Kevin Costner, the intelligent young actor of Field of Dreams, who directed the film and shows a command of story and of visual structure that is startling; this movie moves so confidently and looks so good it seems incredible that it's a directorial debut.",
                "It is a great film for many reasons, not the least of which is that it can be enjoyed as a political thriller as well as a political statement.",
                "Good films about modern American crimes have been few and far between in the last half-dozen years, and \"The French Connection\" beautifully fills the void.",
                "There is only one problem with the excitement generated by this film. After it is over, you will walk out of the theater and, as I did, curse the tedium of your own life.",
                "\"The Godfather,\" now and maybe forever at the Chicago Theater, ends with a door being closed in the face of the audience, and it is because we have been behind that door for nearly three hours that the film has such remarkable appeal.",
                "\"Sleeper\" has plenty of bald spots, lacks the inspired silent comedy of \"Take the Money and Run,\" but, these days, comedy beggars can't be choosers. Woody Allen is about all we've got. And Woody, please stay healthy."
        });
        labeledText.setFocus(5);
        Features.extractFeatures(db, labeledText);
    }
}